-- require("codecompanion").setup({
-- 	strategies = {
-- 		inline = {
-- 			adapter = "anthropic", --change to copilot if out of tokens
-- 		},
-- 		chat = {
-- 			adapter = "anthropic", --change to copilot if out of tokens
-- 			slash_commands = {
-- 				buffer = {
-- 					opts = {
-- 						provider = "telescope",
-- 					},
-- 				},
-- 				file = {
-- 					opts = {
-- 						provider = "telescope",
-- 					},
-- 				},
-- 				help = {
-- 					opts = {
-- 						provider = "telescope",
-- 					},
-- 				},
-- 				symbols = {
-- 					opts = {
-- 						provider = "telescope",
-- 					},
-- 				},
-- 			},
-- 		},
-- 	},
-- 	display = {
-- 		chat = {
-- 			render_headers = false,
-- 			window = {
-- 				width = 0.2,
-- 			},
-- 		},
-- 	},
-- 	adapters = {
-- 		anthropic = function()
-- 			return require("codecompanion.adapters").extend("anthropic", {
-- 				env = {
-- 					api_key = os.getenv("ANTHROPIC_API_KEY"),
-- 				},
-- 				schema = {
-- 					model = {
-- 						default = "claude-3-5-sonnet-20241022",
-- 					},
-- 				},
-- 			})
-- 		end,
-- 	},
-- })
--
-- vim.api.nvim_set_keymap("n", "<leader>a", "<cmd>CodeCompanionActions<cr>", { noremap = true, silent = true })
-- vim.api.nvim_set_keymap("v", "<leader>a", "<cmd>CodeCompanionActions<cr>", { noremap = true, silent = true })
-- vim.api.nvim_set_keymap("n", "<leader>i", "<cmd>CodeCompanion<cr>", { noremap = true, silent = true })
-- vim.api.nvim_set_keymap("v", "<leader>i", ":'<,'>CodeCompanion<cr>", { noremap = true, silent = true })
-- vim.api.nvim_set_keymap("n", "<leader>c", "<cmd>CodeCompanionChat Toggle<cr>", { noremap = true, silent = true })
-- vim.api.nvim_set_keymap("v", "<leader>c", "<cmd>CodeCompanionChat Toggle<cr>", { noremap = true, silent = true })
-- vim.api.nvim_set_keymap("v", "ga", "<cmd>CodeCompanionChat Add<cr>", { noremap = true, silent = true })
--
-- -- Expand 'cc' into 'CodeCompanion' in the command line
-- vim.cmd([[cab cc CodeCompanion]])
