set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm-256color:RGB"

unbind C-b
set -g prefix C-a
bind C-a send-prefix

unbind %
bind i split-window -h

unbind '"'
bind - split-window -v

unbind p
bind p display-popup -E "~/.dotfiles/scripts/projects.zsh"

unbind r
bind r source-file ~/.tmux.conf
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

unbind -T copy-mode-vi MouseDragEnd1Pane

set -sg escape-time 10
set -g allow-passthrough on
set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Kanagawa theme configuration
set -g @plugin 'Steven0351/kanagawa-tmux'
set -g @kanagawa_flavor "wave"

set -g @kanagawa_date_time_text " %H:%M"

set -g @kanagawa_status_background "none"
set -g @kanagawa_status_fill "icon"

set -g @kanagawa_window_number_position "right"
set -g @kanagawa_window_default_fill "number"
set -g @kanagawa_window_default_text "#W"
set -g @kanagawa_window_current_fill "number"
set -g @kanagawa_window_current_text "#W#{?window_zoomed_flag,(),}"

set -g status-left "#{E:@kanagawa_status_session}"
set -g status-right "#{E:@kanagawa_status_directory}#{E:@kanagawa_status_date_time}"
set -g status-right-length 100
set -g status-left-length 100

set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-layout 'reverse'
set -g @sessionx-bind 's'

set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.dotfiles/tmux/plugins/tpm/tpm'

set -g popup-style 'bg=default'
